name: wvn
channels:
  - pytorch
  - robostack
  - robostack-experimental
  - conda-forge
  - pyg
  - defaults
dependencies:
  - python=3.8
  - kornia=0.6.6
  - pip
  - torchvision=0.12
  - pytorch=1.11.0
  - torchaudio
  - cudatoolkit=11.3
  - pytest
  - scipy
  - scikit-image
  - scikit-learn
  - ros-noetic-ros-base
  - ros-noetic-cv-bridge
  - libopencv
  - compilers
  - cmake
  - pkg-config
  - make
  - ninja
  - catkin_tools
  - pyg
  - neptune-client
  - simple-parsing
  - matplotlib
  - seaborn
  - pandas
  - torchmetrics==0.11.0
  - pip:
    - neptune-client[optuna]
    - wandb
    - wget
    - hydra-core
    - pytorch_lightning==1.6.5
    - colorama
    - kornia_rs
    - fast_slic
    - git+https://github.com/lucasb-eyer/pydensecrf.git#egg=pydensecrf
    - git+https://github.com/kornia/kornia#egg=kornia
    - git+https://github.com/mmattamala/liegroups#egg=liegroups
    - --editable git+https://github.com/leggedrobotics/stego.git#egg=stego==0.0.1
    - pytictac
    - prettytable
    - termcolor
