# Input topics
robot_state_topic: "/wild_visual_navigation_node/robot_state"
desired_twist_topic: "/motion_reference/command_twist"
# desired_twist_topic: "/log/state/desiredRobotTwist"

# Relevant frames
fixed_frame: odom
base_frame: base
footprint_frame: footprint

# Robot size
robot_length: 0.8
robot_width: 0.4
robot_height: 0.3

# Robot specs
robot_max_velocity: 0.8

# Traversability estimation params
traversability_radius: 8.0 # meters
image_graph_dist_thr: 0.2 # meters
proprio_graph_dist_thr: 0.1 # meters
network_input_image_height: 448 # 448
network_input_image_width: 448 # 448
segmentation_type: "slic"
feature_type: "dino"
dino_patch_size: 8 # DINO only, 16
slic_num_components: 500
confidence_std_factor: 4.0
scale_traversability: False  # This parameter needs to be false when using the anomaly detection model
scale_traversability_max_fpr: 0.25
min_samples_for_training: 5
prediction_per_pixel: False
traversability_threshold: 0.55
clip_to_binary: False
anomaly_detection: True
vis_training_samples: True

# Supervision Generator
untraversable_thr: 0.01

mission_name: "test"
mission_timestamp: True

# Threads
image_callback_rate: 10 # hertz
proprio_callback_rate: 4 # hertz
learning_thread_rate: 10 # hertz
logging_thread_rate: 2 # hertz
status_thread_rate: 0.5 # hertz

# Runtime options
device: "cuda"
mode: "online" # check out comments in the class WVNMode
colormap: "RdYlBu"

print_image_callback_time: false
print_proprio_callback_time: false
log_time: false
log_confidence: false
verbose: true
debug_supervision_node_index_from_last: 10
use_debug_for_desired: false

extraction_store_folder:  "nan"
exp: "nan"
use_binary_only: true
