# TODO split into three configuration files - shared - learning - feature_extractor

# Input topics
robot_state_topic: "/wild_visual_navigation_node/robot_state"
desired_twist_topic: "/motion_reference/command_twist"
# desired_twist_topic: "/log/state/desiredRobotTwist"

# Relevant frames
fixed_frame: odom
base_frame: base
footprint_frame: footprint

# Robot size
robot_length: 0.8
robot_width: 0.4
robot_height: 0.3


# Traversability estimation params
traversability_radius: 3.0 # meters
image_graph_dist_thr: 0.2 # meters
supervision_graph_dist_thr: 0.1 # meters
network_input_image_height: 224 # 448
network_input_image_width: 224 # 448
segmentation_type: "slic"
feature_type: "dino" # TODO verify this here
dino_patch_size: 8 # 8 or 16; 8 is finer
slic_num_components: 100
dino_dim: 384 # 90 or 384; 384 is better
confidence_std_factor: 4.0
scale_traversability: False  # This parameter needs to be false when using the anomaly detection model
scale_traversability_max_fpr: 0.25
min_samples_for_training: 5
prediction_per_pixel: False
traversability_threshold: 0.55
clip_to_binary: False
vis_node_index: 10

# Supervision Generator
untraversable_thr: 0.01
mission_name: "test"
mission_timestamp: True

# Threads
image_callback_rate: 10 # hertz
supervision_callback_rate: 10 # hertz
learning_thread_rate: 10 # hertz
logging_thread_rate: 2 # hertz
status_thread_rate: 0.5 # hertz

# Runtime options
device: "cuda"
mode: "online" # check out comments in the class WVNMode
colormap: "RdYlBu"

print_image_callback_time: false
print_supervision_callback_time: false
log_time: false
log_confidence: false
verbose: false
debug_supervision_node_index_from_last: 10
use_debug_for_desired: false

extraction_store_folder:  "nan"
exp: "nan"
use_binary_only: true
