# Input topics
robot_state_topic: "/wild_visual_navigation_node/robot_state"
# desired_twist_topic: "/motion_reference/command_twist"
desired_twist_topic: "/log/state/desiredRobotTwist"

camera_topics:
  front:
    image_topic: "/alphasense_driver_ros/cam4/debayered"
    info_topic: "/alphasense_driver_ros/cam4/camera_info"
    use_for_training: true
  # left:
  #   image_topic: "/alphasense_driver_ros/cam3/debayered"
  #   info_topic: "/alphasense_driver_ros/cam3/camera_info"
  #   use_for_training: false
  # right:
  #   image_topic: "/alphasense_driver_ros/cam5/debayered"
  #   info_topic: "/alphasense_driver_ros/cam5/camera_info"
  #   use_for_training: false


# Relevant frames
fixed_frame: odom
base_frame: base
footprint_frame: footprint

# Robot size
robot_length: 1.0
robot_width: 0.6
robot_height: 0.3

# Robot specs
robot_max_velocity: 0.8

# Traversability estimation params
traversability_radius: 3.0 # meters
image_graph_dist_thr: 0.2 # meters
proprio_graph_dist_thr: 0.1 # meters
network_input_image_height: 224 # 448
network_input_image_width: 224 # 448
segmentation_type: "random"
feature_type: "dino"
dino_patch_size: 16 # DINO only
confidence_std_factor: 1.0
scale_traversability: True
scale_traversability_max_fpr: 0.15
min_samples_for_training: 5


# Optical flow params
optical_flow_estimator_type: "none"

# Supervision Generator
untraversable_thr: 0.01

mission_name: "test"
mission_timestamp: True

# Threads
image_callback_rate: 3 # hertz
proprio_callback_rate: 4 # hertz
learning_thread_rate: 10 # hertz
logging_thread_rate: 2 # hertz

# Runtime options
device: "cuda"
mode: "online" # check out comments in the class WVNMode
colormap: "RdYlBu"

print_image_callback_time: false
print_proprio_callback_time: false
log_time: true
log_memory: true
log_confidence: true
verbose: false
debug_supervision_node_index_from_last: 10

use_debug_for_desired: true
extraction_store_folder:  "nan"
exp: "nan"
