services:
  wvn_nvidia:
    extends:
      file: docker-compose-gui.yaml
      service: wvn
    environment:
     - NVIDIA_VISIBLE_DEVICES=all
     - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia